using System.Linq;
using System.Text;
using System.Threading.Tasks;
using PortWerks.Core.Models;

namespace PortWerks.Core.Export
{
    public class HtmlExporter : IExporter
    {
        public string FileExtension => ".html";

        public Task<string> ExportAsync(ScanResult result)
        {
            var sb = new StringBuilder();

            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html>");
            sb.AppendLine("<head>");
            sb.AppendLine("    <meta charset='UTF-8'>");
            sb.AppendLine("    <title>Port Werks Scan Report</title>");
            sb.AppendLine("    <style>");
            sb.AppendLine("        body { font-family: 'Courier New', monospace; background: #0a0a0a; color: #00ff00; padding: 20px; }");
            sb.AppendLine("        h1 { color: #00ff00; border-bottom: 2px solid #00ff00; }");
            sb.AppendLine("        table { border-collapse: collapse; width: 100%; margin: 20px 0; }");
            sb.AppendLine("        th, td { border: 1px solid #00ff00; padding: 8px; text-align: left; }");
            sb.AppendLine("        th { background: #1a1a1a; }");
            sb.AppendLine("        tr:hover { background: #1a1a1a; }");
            sb.AppendLine("        .open { color: #00ff00; font-weight: bold; }");
            sb.AppendLine("        .closed { color: #ff0000; }");
            sb.AppendLine("        .filtered { color: #ffaa00; }");
            sb.AppendLine("        .summary { background: #1a1a1a; padding: 15px; margin: 20px 0; border: 1px solid #00ff00; }");
            sb.AppendLine("        .vuln { color: #ff6600; font-style: italic; }");
            sb.AppendLine("    </style>");
            sb.AppendLine("</head>");
            sb.AppendLine("<body>");

            sb.AppendLine("    <h1>Port Werks Security Scan Report</h1>");

            sb.AppendLine("    <div class='summary'>");
            sb.AppendLine($"        <strong>Target:</strong> {result.TargetHost}<br>");
            sb.AppendLine($"        <strong>Scan Time:</strong> {result.ScanStartTime:yyyy-MM-dd HH:mm:ss} - {result.ScanEndTime:yyyy-MM-dd HH:mm:ss}<br>");
            sb.AppendLine($"        <strong>Duration:</strong> {result.Duration.TotalSeconds:F2} seconds<br>");
            sb.AppendLine($"        <strong>Total Ports:</strong> {result.Statistics.TotalPorts}<br>");
            sb.AppendLine($"        <strong>Open Ports:</strong> {result.Statistics.OpenPorts}<br>");
            sb.AppendLine($"        <strong>Closed Ports:</strong> {result.Statistics.ClosedPorts}<br>");
            sb.AppendLine($"        <strong>Filtered Ports:</strong> {result.Statistics.FilteredPorts}<br>");
            sb.AppendLine($"        <strong>Scan Speed:</strong> {result.Statistics.PortsPerSecond:F2} ports/sec<br>");
            if (!string.IsNullOrEmpty(result.OperatingSystem))
            {
                sb.AppendLine($"        <strong>OS Detection:</strong> {result.OperatingSystem}<br>");
            }
            sb.AppendLine("    </div>");

            sb.AppendLine("    <h2>Port Scan Results</h2>");
            sb.AppendLine("    <table>");
            sb.AppendLine("        <tr>");
            sb.AppendLine("            <th>Port</th>");
            sb.AppendLine("            <th>State</th>");
            sb.AppendLine("            <th>Protocol</th>");
            sb.AppendLine("            <th>Service</th>");
            sb.AppendLine("            <th>Version</th>");
            sb.AppendLine("            <th>Response Time</th>");
            sb.AppendLine("            <th>Banner</th>");
            sb.AppendLine("            <th>Vulnerability Hints</th>");
            sb.AppendLine("        </tr>");

            foreach (var port in result.PortResults)
            {
                var stateClass = port.State.ToString().ToLower();
                sb.AppendLine("        <tr>");
                sb.AppendLine($"            <td>{port.Port}</td>");
                sb.AppendLine($"            <td class='{stateClass}'>{port.State}</td>");
                sb.AppendLine($"            <td>{port.Protocol}</td>");
                sb.AppendLine($"            <td>{port.ServiceName ?? "-"}</td>");
                sb.AppendLine($"            <td>{port.ServiceVersion ?? "-"}</td>");
                sb.AppendLine($"            <td>{port.ResponseTime.TotalMilliseconds:F2} ms</td>");
                sb.AppendLine($"            <td><pre>{EscapeHtml(port.Banner)}</pre></td>");
                sb.AppendLine($"            <td class='vuln'>{string.Join("<br>", port.VulnerabilityHints.Select(EscapeHtml))}</td>");
                sb.AppendLine("        </tr>");
            }

            sb.AppendLine("    </table>");
            sb.AppendLine("    <footer style='margin-top: 40px; text-align: center; color: #666;'>");
            sb.AppendLine("        Generated by Port Werks - Professional Red Team Scanner");
            sb.AppendLine("    </footer>");
            sb.AppendLine("</body>");
            sb.AppendLine("</html>");

            return Task.FromResult(sb.ToString());
        }

        private string EscapeHtml(string? value)
        {
            if (string.IsNullOrEmpty(value)) return "-";
            return value
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;");
        }
    }
}
